
export const bookMap: Record<string, string> = {
  // Pentateuco
  'Gn': 'Gênesis',
  'Êx': 'Êxodo',
  'Lv': 'Levítico',
  'Nm': 'Números',
  'Dt': 'Deuteronômio',
  // Livros Históricos
  'Js': 'Josué',
  'Jz': 'Juízes',
  'Rt': 'Rute',
  '1Sm': '1 Samuel',
  '2Sm': '2 Samuel',
  '1Rs': '1 Reis',
  '2Rs': '2 Reis',
  '1Cr': '1 Crônicas',
  '2Cr': '2 Crônicas',
  'Ed': 'Esdras',
  'Ne': 'Neemias',
  'Et': 'Ester',
  // Livros Poéticos
  'Jó': 'Jó',
  'Sl': 'Salmos',
  'Pv': 'Provérbios',
  'Ec': 'Eclesiastes',
  'Ct': 'Cânticos',
  // Profetas Maiores
  'Is': 'Isaías',
  'Jr': 'Jeremias',
  'Lm': 'Lamentações',
  'Ez': 'Ezequiel',
  'Dn': 'Daniel',
  // Profetas Menores
  'Os': 'Oseias',
  'Jl': 'Joel',
  'Am': 'Amós',
  'Ob': 'Obadias',
  'Jn': 'Jonas',
  'Mq': 'Miqueias',
  'Na': 'Naum',
  'Hc': 'Habacuque',
  'Sf': 'Sofonias',
  'Ag': 'Ageu',
  'Zc': 'Zacarias',
  'Ml': 'Malaquias',
  // Evangelhos
  'Mt': 'Mateus',
  'Mc': 'Marcos',
  'Lc': 'Lucas',
  'Jo': 'João',
  // Histórico
  'At': 'Atos',
  // Epístolas Paulinas
  'Rm': 'Romanos',
  '1Co': '1 Coríntios',
  '2Co': '2 Coríntios',
  'Gl': 'Gálatas',
  'Ef': 'Efésios',
  'Fp': 'Filipenses',
  'Cl': 'Colossenses',
  '1Ts': '1 Tessalonicenses',
  '2Ts': '2 Tessalonicenses',
  '1Tm': '1 Timóteo',
  '2Tm': '2 Timóteo',
  'Tt': 'Tito',
  'Fm': 'Filemom',
  // Epístolas Gerais
  'Hb': 'Hebreus',
  'Tg': 'Tiago',
  '1Pe': '1 Pedro',
  '2Pe': '2 Pedro',
  '1Jo': '1 João',
  '2Jo': '2 João',
  '3Jo': '3 João',
  'Jd': 'Judas',
  // Apocalipse
  'Ap': 'Apocalipse',
};
