export const bookMap: Record<string, string> = {
  // Pentateuco
  'Gn': 'GEN',
  'Êx': 'EXO',
  'Lv': 'LEV',
  'Nm': 'NUM',
  'Dt': 'DEU',
  // Livros Históricos
  'Js': 'JOS',
  'Jz': 'JDG',
  'Rt': 'RUT',
  '1Sm': '1SA',
  '2Sm': '2SA',
  '1Rs': '1KI',
  '2Rs': '2KI',
  '1Cr': '1CH',
  '2Cr': '2CH',
  'Ed': 'EZR',
  'Ne': 'NEH',
  'Et': 'EST',
  // Livros Poéticos
  'Jó': 'JOB',
  'Sl': 'PSA',
  'Pv': 'PRO',
  'Ec': 'ECC',
  'Ct': 'SNG',
  // Profetas Maiores
  'Is': 'ISA',
  'Jr': 'JER',
  'Lm': 'LAM',
  'Ez': 'EZK',
  'Dn': 'DAN',
  // Profetas Menores
  'Os': 'HOS',
  'Jl': 'JOL',
  'Am': 'AMO',
  'Ob': 'OBA',
  'Jn': 'JON',
  'Mq': 'MIC',
  'Na': 'NAM',
  'Hc': 'HAB',
  'Sf': 'ZEP',
  'Ag': 'HAG',
  'Zc': 'ZEC',
  'Ml': 'MAL',
  // Evangelhos
  'Mt': 'MAT',
  'Mc': 'MRK',
  'Lc': 'LUK',
  'Jo': 'JHN',
  // Histórico
  'At': 'ACT',
  // Epístolas Paulinas
  'Rm': 'ROM',
  '1Co': '1CO',
  '2Co': '2CO',
  'Gl': 'GAL',
  'Ef': 'EPH',
  'Fp': 'PHP',
  'Cl': 'COL',
  '1Ts': '1TH',
  '2Ts': '2TH',
  '1Tm': '1TI',
  '2Tm': '2TI',
  'Tt': 'TIT',
  'Fm': 'PHM',
  // Epístolas Gerais
  'Hb': 'HEB',
  'Tg': 'JAS',
  '1Pe': '1PE',
  '2Pe': '2PE',
  '1Jo': '1JN',
  '2Jo': '2JN',
  '3Jo': '3JN',
  'Jd': 'JUD',
  // Apocalipse
  'Ap': 'REV',
};
